name: screen_identifier
description: A package provides an easy way to adjust multiple values based on screen size or parent widget size in Flutter project.
version: 0.0.2
repository: https://github.com/msuhal/flutter_screen_identifier
issue_tracker: https://github.com/msuhal/flutter_screen_identifier/issues

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
